# Generated by Django 5.2.1 on 2025-07-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='File',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
